### ISSUE TITLE
Usual checklist review

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/node-manager#1]
- [x] Does the project have a `README.md` ?
- [x] Does the project have a `LICENSE` file?
- [x] Does the project have a [GitHub Action](https://github.com/features/actions)?
    - [x] Does it upload the code coverage somewhere?
    - [x] Does it manage the release of the code? (Continuous Delivery) ⇒ *Done in 97101dafe585f22c006e579da44b3373564bb1d1*
- [x] Does it have a DockerFile or does it need it? ⇒ *Done in 97101dafe585f22c006e579da44b3373564bb1d1*

Bonus track
- [x] Make sure the `.reuse` metadata is correct (it is not right now) ⇒ *Done in  dc23555f450a47625a8c63c86c24dc7e59756024*
- [x] Compact the CI to not try to run on multiple platforms actions that have the same outcome

Thank you!

**Comment by arpad-m** [comment]
> Does it have a DockerFile or does it need it?

This component is implemented as a library crate and used by the DHT crate. It is not meant to be ran standalone. Thus, a dockerfile is not required.

**Comment by arpad-m** [comment]
> Does it manage the release of the code? (Continuous Delivery)

I have removed the deploy job in a42d6ca90115e8541392c93fab50d39a20c2fda8 , as it was uploading binaries which is not useful for a library crate. We could discuss uploading to crates.io with an action, but I think that the crate won't be very useful to people outside of SIFIS-home. I'd suggest just using a git dependency from the DHT.

**Comment by lu-zero** [comment]
If a partner wants to take the maintainership post-project it could make sense, but does not require to make the decision now.

**Comment by arpad-m** [comment]
I've compactified the CI and also the code coverage works, both with help of @Luni-4.

I'm not entirely sure yet about how the node manager should be integrated however, depending on the integration maybe a dockerfile is needed after all. I don't know.

**Comment by Luni-4** [comment]
Perhaps you can create a `Dockerfile` that builds the node manager and sets up its dependencies. Then you can run the container that runs the `node-manager`. You can pass `node-manager` parameters through docker at runtime also. Could it be an idea?

**Comment by arpad-m** [comment]
I have taken the CD code from the dht component and modified it for the node-manager, see commit 97101dafe585f22c006e579da44b3373564bb1d1 . Therefore, this should be resolved now. Please comment if you want me to do something from that point of view.
